#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
# Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#

trap ":" INT QUIT TSTP

##
# setup rootfs
#

mkdir -p /dev /proc /sys /tmp /var

/bin/mount -n -t proc none /proc
/bin/mount -n -t sysfs none /sys
#/bin/mount -n -t usbfs none /proc/bus/usb
/bin/mount -t ramfs none /dev

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

mkdir -p /dev/pts
mkdir -p /dev/shm
/bin/mount -n -t devpts none /dev/pts -o mode=0622
/bin/mount -n -t tmpfs tmpfs /dev/shm
/bin/mount -n -t ramfs none /tmp
/bin/mount -n -t ramfs none /var
mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

##
# routines
#

/sbin/hwclock -s -f /dev/rtc

/sbin/syslogd

/sbin/ifconfig lo 127.0.0.1
/etc/init.d/ifconfig-eth0

/usr/sbin/telnetd
tcpsvd -vE 0.0.0.0 21 ftpd /srv &
